- platform: mqtt
  name: "Brick wall accent"
  state_topic: "home/rgb2"
  command_topic: "home/rgb2/set"
  brightness: true
  rgb: true
  optimistic: false
  effect: true
  effect_list:
    - solid
    - rainbow
  qos: 0
- platform: mqtt
  name: "Camera lamp"
  state_topic: "state_fb_1-552711"
  command_topic: "state_cmd_1-552711"
  brightness_command_topic: "state_cmd_1-552711"
  brightness_state_topic: "led1_fb-552711"
- platform: mqtt
  name: "Desk lamp"
  state_topic: "state_fb_1-1322583"
  command_topic: "state_cmd_1-1322583"
  brightness_command_topic: "state_cmd_1-1322583"
  brightness_state_topic: "led1_fb-1322583"
- platform: mqtt
  name: "TV"
  state_topic: "state_fb_1-552302"
  command_topic: "state_cmd_1-552302"
  brightness_command_topic: "state_cmd_1-552302"
  brightness_state_topic: "led1_fb-552302"
- platform: mqtt_json
  name: Glass cabinet lights
  state_topic: "home/rgb1"
  command_topic: "home/rgb1/set"
  brightness: true
  rgb: true
  optimistic: false
  effect: true
  effect_list:
    - solid
    - rainbow
  qos: 0
