- platform: mqtt
  name: "Brick wall accent"
  state_topic: "state_fb_1-552304"
  command_topic: "state_cmd_1-552304"
  brightness_command_topic: "state_cmd_1-552304"
  brightness_state_topic: "led1_fb-552304"
