- platform: octoprint
  name: Printer status
  monitored_conditions:
   - Current State
   - Temperatures
   - Job Percentage
- platform: miflora
  name: Pepper
  mac: "C4:7C:8D:63:59:AD"
  median: 3
  monitored_conditions:
   - temperature
   - moisture
   - light
   - conductivity
   - battery
- platform: miflora
  name: Ivy
  mac: "C4:7C:8D:63:7E:2E"
  median: 3
  monitored_conditions:
   - temperature
   - moisture
   - light
   - conductivity
   - battery
- platform: miflora
  name: Yucca
  mac: "C4:7C:8D:63:8B:9D"
  median: 3
  monitored_conditions:
   - temperature
   - moisture
   - light
   - conductivity
   - battery
- platform: miflora
  name: Basil
  mac: "C4:7C:8D:63:8B:34"
  median: 3
  monitored_conditions:
   - temperature
   - moisture
   - light
   - conductivity
   - battery
- platform: miflora
  name: Pilea
  mac: "C4:7C:8D:63:8B:D7"
  median: 3
  monitored_conditions:
   - temperature
   - moisture
   - light
   - conductivity
   - battery
- platform: speedtest
  minute:
   - 2
   - 17
   - 32
   - 47
  monitored_conditions:
   - ping
   - download
   - upload
- platform: cpuspeed
  name: CPU
- platform: systemmonitor
  resources:
   - type: disk_use_percent
     arg: /
   - type: disk_use_percent
     arg: /var/log
   - type: memory_use_percent
   - type: memory_use
   - type: memory_free
   - type: processor_use
   - type: swap_use_percent
   - type: swap_use
   - type: swap_free
   - type: last_boot
   - type: since_last_boot
   - type: network_in
     arg: eth0
   - type: network_out
     arg: eth0
   - type: packets_in
     arg: eth0
   - type: packets_out
     arg: eth0
   - type: ipv4_address
     arg: eth0
   - type: ipv6_address
     arg: eth0
   - type: network_in
     arg: eth1
   - type: network_out
     arg: eth1
   - type: packets_in
     arg: eth1
   - type: packets_out
     arg: eth1
   - type: ipv4_address
     arg: eth1
   - type: ipv6_address
     arg: eth1
- platform: time_date
  display_options:
   - 'time'
   - 'date'
   - 'date_time'
   - 'time_date'
   - 'time_utc'
   - 'beat'
- platform: mqtt
  name: "Living room temperature"
  state_topic: "Temp12846772"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Living room humidity"
  state_topic: "Humid12846772"
  unit_of_measurement: "%"
- platform: mqtt
  name: "Bedroom temperature"
  state_topic: "Temp664073"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Bedroom humidity"
  state_topic: "Humid664073"
  unit_of_measurement: "%"
- platform: mqtt
  name: "Bedroom CO2"
  state_topic: "CO2664073"
  unit_of_measurement: "ppm"
- platform: mqtt
  name: "Guest room temperature"
  state_topic: "Temp12841218"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Guest room humidity"
  state_topic: "Humid12841218"
  unit_of_measurement: "%"
- platform: template
  sensors:
    alarm_hour:
      friendly_name: 'Hour'
      value_template: '{{ states.input_number.alarmhour.state|round(0)|string }}'
    alarm_minutes:
      friendly_name: 'Minutes'
      value_template: '{{ states.input_number.alarmminutes.state|round(0)|string }}'
    alarm_time:
      friendly_name: 'Alarm'
      value_template: '{% if states.input_select.bedroom_alarm_hours.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_select.bedroom_alarm_hours.state|round(0)|string }}:{% if states.input_select.bedroom_alarm_min.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_select.bedroom_alarm_min.state|round(0)|string }}'
    current_time:
      value_template: '{{ now().strftime("%H:%M")}}'
    day_time:
      friendly_name: 'Day time'
      value_template: '{% if states.input_number.day_time_hr.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.day_time_hr.state|round(0)|string }}:{% if states.input_number.day_time_min.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.day_time_min.state|round(0)|string }}'
    night_time:
      friendly_name: 'Night time'
      value_template: '{% if states.input_number.night_time_hr.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.night_time_hr.state|round(0)|string }}:{% if states.input_number.night_time_min.state|round(0)|string|length == 1 %}0{% endif %}{{ states.input_number.night_time_min.state|round(0)|string }}'
- platform: template
  sensors:
    livingroom_setpoint:
      value_template: '{{ states.climate.livingroom.attributes.temperature }}'
      friendly_name: 'Living room setpoint'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    bedroom_setpoint:
      value_template: '{{ states.climate.bedroom.attributes.temperature }}'
      friendly_name: 'Bedroom setpoint'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    guestroom_setpoint:
      value_template: '{{ states.climate.guestroom.attributes.temperature }}'
      friendly_name: 'Guest room setpoint'
      unit_of_measurement: '°C'
- platform: yweather
  monitored_conditions:
   - weather
   - weather_current
   - temp_min
   - temp_max
   - wind_speed
   - pressure
   - visibility
   - humidity
   - temperature
